
struct DownloadList {
  char const * URL;
  char const * filename;
};


// try to reduce filename on fail!
const DownloadList download_list[] = {

  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/16k/Battlezone-6000.prg", "Battlezone 60.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/16k/Battlezone-a000.prg", "Battlezone A0.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games.basic/unexpanded/Vic%20Blitz.prg", "Blitz.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games/unexpanded/Abductor.prg", "Abductor.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Aggressor.prg", "Aggressor.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games/unexpanded/Alien%20Attack.prg", "Alien Attack.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games/unexpanded/Alien%20Blitz.PAL.prg", "Alien Blitz.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/4k/Amok!.prg", "Amok.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Apple%20Panic-6000.prg", "Apple Panic 60.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Apple%20Panic-a000.prg", "Apple Panic A0.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games/unexpanded/Arcadia.prg", "Arcadia.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Attack%20of%20the%20Mutant%20Camels.prg", "Attack Mut. Cam.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Avenger.prg", "Avenger.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/16k/Battlezone-6000.prg", "Battlezone 60.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/16k/Battlezone-a000.prg", "Battlezone A0.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games/unexpanded/Blockbuster.prg", "Blockbuster.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games/unexpanded/Bomber.prg", "Bomber.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games.basic/unexpanded/Break%20Out%204.prg", "Breakout.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/16k/Centipede-2000.prg", "Centipede 20.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/16k/Centipede-a000.prg", "Centipede A0.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Choplifter.prg", "Choplifter.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games/8k/Cosmic%20Firebirds.prg", "Cosmic Firebirds 16K.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Crossfire.PAL.prg", "Crossfire.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Cyclon.prg", "Cyclon.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/D'Fuse.prg", "D'Fuse.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/4k/Demon%20Attack.PAL.prg", "Demon Attack.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/16k/Donkey%20Kong-2000.prg", "Donkey Kong 20.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/16k/Donkey%20Kong-a000.prg", "Donkey Kong A0.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Dragonfire.prg", "Dragonfire.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Frogger.prg", "Frogger.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Galaxian.prg", "Galaxian.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Garden%20Wars.prg", "Garden Wars.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Jelly%20Monsters.prg", "Jelly Monsters.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Jupiter%20Lander.prg", "Jupiter Lander.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/KeyQuest.prg", "Key Quest.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Lazerzone.prg", "Lazerzone.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games/8k/Matrix.prg", "Matrix 8K.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Miner%202049'er.prg", "Miner 2049.CRT" }, //....NON PARTE
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Mole%20Attack.prg", "Mole Attack.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Omega%20Race.prg", "Omega Race.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Outworld.prg", "Outworld.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Pac-Man.prg", "PacMan.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Polaris.prg", "Polaris.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/16k/Pole%20Position-6000.prg", "Pole Position 60.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/16k/Pole%20Position-a000.prg", "Pole Position A0.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Protector.prg", "Protector.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Quackers.prg", "Quackers.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/River%20Rescue.prg", "River Rescue.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Robot%20Panic.prg", "Robot Panic.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/4k/Satellite%20Patrol.prg", "Satellite Patrol.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Satellites%20and%20Meteorites.PAL.prg", "Satellites & Met.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Scorpion.prg", "Scorpion.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Serpentine.PAL.prg", "Serpentine.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Shamus.prg", "Shamus.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Spiders%20of%20Mars-6000.prg", "Spiders Mars 60.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Spiders%20of%20Mars-a000.prg", "Spiders Mars A0.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Star%20Battle.prg", "Star Battle.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Star%20Trek%20-%20S.O.S.prg", "Star Trek SOS.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/4k/Sub%20Chase.prg", "Sub Chase.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Super%20Amok.prg", "Super Amok.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Super%20Smash.prg", "Super Smash.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/4k/Terraguard.prg", "Terraguard.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/roms/8k/Threshold.prg", "Threshold.CRT" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games/16k/Tom.prg", "Tom 16K.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Witch%20Way%201983%20CDS%20NTSC%20A000.crt", "Witch Way A0.CRT" },
  { "http://cloud.cbm8bit.com/adamcost/Midnight%20Drive%20Commodore%20A000.crt", "Road Race A0.CRT" },
  { "http://cloud.cbm8bit.com/adamcost/Car%20Race%20Commodore.prg", "Car Race.PRG" },
  { "http://www.zimmers.net/anonftp/pub/cbm/vic20/games/8k/Tron.prg", "Tron 8K.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Wall%20Defense.prg", "Wall Defence.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Tower%20of%20Evil%201984%20Thorn%20Emi%208K.prg", "Tower Of Evil 8K.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Thunder%20Flash%201983%20Temptation.prg", "Thunder Flash.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/The%20Catch.prg", "The Catch.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Space%20Phreaks%201982.prg", "Space Phreaks.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Skramble%20Anirog%2016K.prg", "Skramble 16K.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Perilous%20Caavern%2016k.prg", "Perilous Caa. 16K.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Orbis.prg", "Orbis.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Meteor%20Run%208K.prg", "Meteor Run 8K.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Hellgate%208K.prg", "Hellgate 8K.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Gladiator.prg", "Gladiator.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Flowers%20of%20Evil%208K.prg", "Flowers Evil 8K.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Fire%20Galaxy%20-%20Kingsoft%2016K.prg", "Fire Galaxy 16K.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Fantasia.prg", "Fantasia.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Falcons%20Lander%208K.prg", "Falcons Land. 8K.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/Defender.prg", "Defender.PRG" },
  { "http://cloud.cbm8bit.com/adamcost/cube%20bert%2016k.prg", "Cube Bert 16K.PRG" },

};


